FassonAPI_ASP/Controllers/IndexController.cs
using FassonAPI_ASP.Models.FaceRegAuth;
using FassonAPI_ASP.Models.DataBase;
using FassonAPI_ASP.Models;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Text;
using System.IO;
using System;


namespace FassonAPI_ASP.Controllers
{
    /// <summary>
    /// Класс для взаимодействия с front-end.
    /// 
    /// Для аутентификации и регистрации используются 
    /// классы AzureDataBase и ModuleFaceAPI.
    /// 
    /// Обрабатывает предсказуемые исключительные ситуации, 
    /// FassonException.
    /// </summary>
    public class IndexController : Controller, FassonAPI.IFassonController
    {
        /// <summary>
        /// Возвращает главную страницу, 
        /// при этом подгружая пользователей.
        /// 
        /// GET: Index
        /// </summary>
        /// <returns>Страница представления FassonAPI</returns>
        [HttpGet]
        public async Task<ActionResult> Index() =>
            View(await AzureDataBase.GetUsers());

        #region Accounts
        /// <summary>
        /// Используется для обновления списка аккаунтов.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public void Accounts() =>
            Redirect("/Index/Index");
        /// <summary>
        /// Запрос на удаление аккаунта.
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<string> DeleteAccount()
        {
            try
            {
                var user = await ReqHandler(Request.InputStream);
                if (string.IsNullOrEmpty(user.Password))
                    throw new FassonException("You must fill the empty fields");

                // AZURE!!! /////////////////
                await new AzureDataBase().DeleteUser(user);
                return true.ToString();
            }
            catch (FassonException e) { return e.Message; }

        }
        #endregion Accounts

        #region RA_WithoutFace
        /// <summary>
        /// Алгоритм регистрации пользователя.
        /// </summary>
        /// <returns>Итоговый статус</returns>
        [HttpPost]
        public async Task<string> Registration()
        {
            try
            {
                var user = await ReqHandler(Request.InputStream);
                if (string.IsNullOrEmpty(user.Password))
                    throw new FassonException("You must fill the empty fields");
                // AZURE!!! /////////////////
                await new AzureDataBase().Registration(user);
                return true.ToString();
            }
            catch (FassonException e) { return e.Message; }
        }
        /// <summary>
        /// Алгоритм аутентификации.
        /// </summary>
        /// <returns>Итоговый статус</returns>
        [HttpPost]
        public async Task<string> Authentication()
        {
            try
            {
                return (await new AzureDataBase().Authentication(
                   await ReqHandler(Request.InputStream))).ToString();
            }
            catch (FassonException e) { return e.Message; }
        }
        #endregion 

        #region RA_WithFace
        /// <summary>
        /// Алгоритм регистрации пользователя.
        /// </summary>
        /// <returns>Итоговый статус</returns>
        [HttpPost]
        public async Task<string> RegFace()
        {
            try
            {
                var user = await ReqHandler(Request.InputStream);

                if (string.IsNullOrEmpty(user.Password))
                    throw new FassonException("You must fill the empty fields");

                if (user.Login.Contains("/"))
                    throw new FassonException("Do not use \"/\" in Login");
                user.FaceID = "usersportraits/" + user.Login + ".png";
                await new ModuleFaceAPI().FaceRegister(user);
                return true.ToString();
            }
            catch (FassonException e) { return e.Message; }
        }
        /// <summary>
        /// Привязывает портрет к определённому пользователю
        /// </summary>
        /// <returns>Итоговый статус</returns>
        [HttpPost]
        public async Task<string> LinkFacePortrait()
        {
            try
            {
                var user = await ReqHandler(Request.InputStream);

                if (string.IsNullOrEmpty(user.Password))
                    throw new FassonException("You must fill the empty fields");

                if (user.Login.Contains("/"))
                    throw new FassonException("Do not use \"/\" in Login");

                try
                {
                    if (!user.Equals(await new AzureDataBase().DownloadUserData(user)))
                        throw new FassonException("Incorrect password");
                }
                catch (FassonException) { throw; }
                catch (Exception) { throw new FassonException("Account is not exist"); }

                user.FaceID = "usersportraits/" + user.Login + ".png";

                await new ModuleFaceAPI().FaceRegister(user);
                return true.ToString();
            }
            catch (FassonException e) { return e.Message; }
        }
        /// <summary>
        /// Алгоритм аутентификации.
        /// </summary>
        /// <returns>Итоговый статус</returns>
        [HttpPost]
        public async Task<string> AuthFace()
        {
            try
            {
                var user = await ReqHandler(Request.InputStream);
                user.FaceID = "usersportraits/" + user.Login + ".png";
                return Task.FromResult((await new ModuleFaceAPI().FaceAuth(user)).ToString()).Result;
            }
            catch (FassonException e) { return e.Message; }
        }
        #endregion

        /// <summary>
        /// Обработка полученных данных с запроса.
        /// </summary>
        /// <param name="request">Полученные данные</param>
        /// <returns>Полученные данные представляются при помощи класса User</returns>
        private static async Task<User> ReqHandler(Stream request)
        {
            string[] req = new string[3];
            byte[] image = null;
            using (var reader = new StreamReader(request))
            {   //Обработка полученного запроса
                //`Login=${Login.value}&Password=${Password.value}&Face=${dataImg}`
                req = (await reader.ReadToEndAsync()).Split('&');
            }
            // Логин
            string login = req[0].Substring(req[0].IndexOf("Login=") + 6);
            if (login.Contains("/"))
                throw new FassonException("Do not use \"/\" in Login");
            if (string.IsNullOrEmpty(login))
                throw new FassonException("You must fill the empty fields");
            // Пароль
            string password = req[1].Substring(req[1].IndexOf("Password=") + 9);

            // Портрет, если таковой есть.
            if (req.Length == 3)
                image = Convert.FromBase64String(
                         req[2].Substring(req[2].IndexOf("base64,") + 7));

            return new User(login, password, portrait: image);
        }
        /// <summary>
        /// Обрабатывает полученные отзывы.
        /// Складирует их в базе данных.
        /// </summary>
        /// <param name="feedBack">Отзыв</param>
        /// <returns>Перенаправляет на главную страницу</returns>
        [HttpPost]
        public async Task<ActionResult> FeedBack(string feedBack)
        {
            await AzureDataBase.UploadData(
                 new MemoryStream(Encoding.UTF8.GetBytes(feedBack)),
                 "FeedBack/_" + DateTime.Now.ToString().Replace('/', '.') + "_.txt",
                 "text/plain");

            return Redirect("~/Index/Index");
        }
    }
}

FassonAPI_ASP/Views/Index/Index.cshtml
@model IEnumerable<FassonAPI_ASP.Models.DataBase.User>
@{
    ViewBag.Title = "FassonAPI";
    Layout = "~/Views/Shared/_DefaultPage.cshtml";
}
<!--Надпись приветствия-->
<div class="welcome-land">
    <article>
        <h1>Рад приветствовать вас на защите моей курсовой работы!</h1>
        <h3 id="welcome-land-h3">Эта страница представляет собой наглядную демонстрацию возможностей <b>Fasson API</b>.</h3>
    </article>
</div>

<!--Блок с регистрацией и аутентификацией.-->
<div class="workspace">

    <form class="corona" style="height:auto;">
        <h3 style="margin-top:0vh; margin-bottom:1vh; color:whitesmoke;">
            Как это работает?
        </h3>
    </form>
    <!--------------РЕГИСТРАЦИЯ-------------->
    <div class="Instruction_manual_UI">
        <h3 class="Instruction_manual_UI">Шаг 1. Регистрация</h3>
        <p class="Instruction_manual_UI">
            Первым делом необходимо зарегистрировать аккаунт, <br />
            к которому в процессе регистрации будет прикреплено лицо.<br /><br />
            Зарегистрируйте лицо сразу или позднее, однако, при этом используйте корректные логин и пароль.
        </p>

        <input name="Login" type="text" class="form-control Registration" aria-describedby="emailHelp" placeholder="Логин" required>
        <input name="Password" type="password" class="form-control Registration" placeholder="Пароль" required>
        <input name="PasswordCheck" type="password" class="form-control Registration" placeholder="Подтверждение пароля" required>

        <button id="btnReg" type="button" class="authorization navbar mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect"
                onclick="Submit('/Index/Registration/');">
            <p class="authorization navbar">Зарегистрироваться</p>
        </button>
        <button type="button" class="authorization navbar mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect"
                id="RegistrPortrait">
            <p class="authorization navbar" id="RegistrPortrait">Прикрепить портрет</p>
        </button>
        <br />
    </div>

    <!--------------СОЗДАНИЕ ПОРТРЕТА-------------->
    <div class="Instruction_manual_UI">
        <h3 class="Instruction_manual_UI">Шаг 1.1 Создание портрета</h3>
        <p class="Instruction_manual_UI">
            Прикрепите лицо к уже существующему аккаунту <br />
        </p>

        <input name="Login" type="text" class="form-control CreatePortrait" aria-describedby="emailHelp" placeholder="Логин" required>
        <input name="Password" type="password" class="form-control CreatePortrait" placeholder="Пароль" required>
        <input name="PasswordCheck" type="password" class="form-control CreatePortrait" placeholder="Подтверждение пароля" required>

        <button type="button" class="authorization navbar mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect"
                id="CreatePortrait">
            <p class="authorization navbar" id="CreatePortrait">Прикрепить портрет</p>
        </button>
        <br />
    </div>

    <!--------------АУТЕНТИФИКАЦИЯ-------------->
    <div class="Instruction_manual_UI">
        <h3 class="Instruction_manual_UI">Шаг 2. Аутентификация</h3>
        <p class="Instruction_manual_UI">
            После того, как пользователь зарегистрирован,<br />
            можно протеситровать возможности аутентификации.
        </p>
        <input name="Login" type="text" class="form-control Auth" aria-describedby="emailHelp" placeholder="Логин" required>
        <input name="Password" type="password" class="form-control Auth" placeholder="Пароль">
        <small id="emailHelp" class="form-text text-muted" style="margin-left: 8px !important">
            Если вы пользуетесь входом по лицу, то вводить пароль не нужно
        </small>
        <button id="btnAuth" type="button" class="authorization navbar  mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect"
                onclick="Submit('/Index/Authentication/');">
            <p class="authorization navbar">Аутентификация</p>
        </button>
        <button type="button" class="authorization navbar mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect"
                id="AuthPortrait">
            <p class="authorization navbar" id="AuthPortrait">Войти, используя лицо</p>
        </button>
        <br />
    </div>

    <!--------------УДАЛЕНИЕ АККАУНТА-------------->
    <div class="Instruction_manual_UI">
        <h3 class="Instruction_manual_UI">Шаг 3. Удаление аккаунта</h3>
        <p class="Instruction_manual_UI">
            После тестирования у пользователя есть опция<br />
            удалить созданный аккаунт.
        </p>
        <input name="Login" type="text" class="form-control AccDel" aria-describedby="emailHelp" placeholder="Логин" required>
        <input name="Password" type="password" class="form-control AccDel" placeholder="Пароль" required>
        <button id="btnAccDel" type="button" class="authorization navbar mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect"
                onclick="Accounts(Controller = '/Index/DeleteAccount/',
        ReqData = `Login=${AD_itLogin.value}&Password=${AD_itPassword.value}`, Type = 'POST');">
            <p class="authorization navbar">Удалить аккаунт</p>
        </button>
        <br />
    </div>

    <!--------------Фидбэк-------------->
    <div class="Instruction_manual_UI" id="testing">
        <h3 class="Instruction_manual_UI">Книга жалоб и предложений</h3>
        <p class="Instruction_manual_UI">
            Опишите ваши впечатления.<br />
        </p>
        @using (Html.BeginForm("FeedBack", "Index", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input name="feedBack" type="text" class="form-control Auth" aria-describedby="emailHelp" placeholder="Напишите отзыв" required>
            <input type="submit" class="form-control Auth" aria-describedby="emailHelp">
        }
    </div>
</div>

<!--Отображение аккаунтов из базы данных.-->
<aside class="Accounts">
    <form class="corona" style="border-radius: 20px;">
        <h3 style="margin-top:0vh; margin-bottom:0vh; color:whitesmoke; ">
            Аккаунты
            <button onclick="Accounts()" class="mdl-button mdl-js-button mdl-button mdl-js-ripple-effect Accounts" style="border-radius: 100px !important; border: none !important;">
                <img src="https://img.icons8.com/clouds/96/000000/cloud-refresh.png" alt="Reload" id="reload" width="50" height="50" />
            </button>
        </h3>

    </form>
    <div class="Accounts">
        @foreach (var user in Model)
        {
            // Поля: логин, пароль, картинка
            if (user.FaceID != null)
            {
                <img class="Accounts" src="data:image/png;base64,@Convert.ToBase64String(user.Portrait)" alt="Alternate Text" />
            }
            <h4 class="Accounts">@user.Login</h4>
            <p class="Accounts">@user.Password</p>

            <hr />
        }
        @if (Model.Count() == 0)
        {
            <br />
            <h4 style="text-align: center">Аккаунтов пока нет</h4>
        }
    </div>
</aside>